#development environment
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/securitypractice
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#file config

spring.security.user.name=rashi
spring.security.user.password=rashindra

#logging.level.org.springframework.security=DEBUG

jwt.secretKey=4T/kpVoYU1F2lGheuFRAE7cVFydWLzwiJVBoHmWKdjY5zffY3xaYJZXO5Mbpt9BNuvNafyhQ8P3q76ITEugxDQ==