#project configuration file
#common configuration:
spring.profiles.active=dev
lcwd.profile.image.path=/home/profile
#custome LCWD configuration
lcwd.config.name=durgesh
lcwd.config.email=dev.learncodewithdurgesh.com
lcwd.config.password=root
lcwd.config.emailExpTime=12
#save the logging into file
logging.file.name=app.log




#Database configuration
spring.datasource.url=jdbc:mysql://localhost:3307/boot_course
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Jpa/Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#dialect
#dialect is actually the version of mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect